name: CI
on:
  pull_request:
  merge_group:

env:
  MDBOOK_VERSION: 0.4.40
  # When updating, be sure to also update rust-lang/rust.
  MDBOOK_SPEC_VERSION: 0.1.0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
        key: ms-${MDBOOK_SPEC_VERSION}
    - name: Update rustup
      run: rustup self update
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install nightly -c rust-docs
        rustup default nightly
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Report versions
      run: |
        rustup --version
        rustc -Vv
        mdbook --version
    - name: Install mdbook-spec
      run: cargo install --locked mdbook-spec@${MDBOOK_SPEC_VERSION}
    - name: Run tests
      run: mdbook test
    - name: Style checks
      run: (cd style-check && cargo run -- ../src)
    - name: Check for broken links
      run: |
        curl -sSLo linkcheck.sh \
          https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
        sh linkcheck.sh --all reference
